/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorder.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API

#import "GTLGraderecorderConstants.h"

#import "GTLGraderecorderAssignment.h"
#import "GTLGraderecorderAssignmentCollection.h"
#import "GTLGraderecorderGradeEntry.h"
#import "GTLGraderecorderGradeEntryCollection.h"
#import "GTLGraderecorderStudent.h"
#import "GTLGraderecorderStudentCollection.h"

#import "GTLQueryGraderecorder.h"
#import "GTLServiceGraderecorder.h"
