/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorderStudent.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API
// Classes:
//   GTLGraderecorderStudent (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGraderecorderStudent
//

@interface GTLGraderecorderStudent : GTLObject
@property (copy) NSString *entityKey;
@property (copy) NSString *firstName;
@property (copy) NSString *lastName;
@property (copy) NSString *roseUsername;
@property (copy) NSString *team;
@end
