/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorderAssignment.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API
// Classes:
//   GTLGraderecorderAssignment (0 custom class methods, 2 custom properties)

#import "GTLGraderecorderAssignment.h"

// ----------------------------------------------------------------------------
//
//   GTLGraderecorderAssignment
//

@implementation GTLGraderecorderAssignment
@dynamic entityKey, name;
@end
