/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorderStudentCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API
// Classes:
//   GTLGraderecorderStudentCollection (0 custom class methods, 2 custom properties)

#import "GTLGraderecorderStudentCollection.h"

#import "GTLGraderecorderStudent.h"

// ----------------------------------------------------------------------------
//
//   GTLGraderecorderStudentCollection
//

@implementation GTLGraderecorderStudentCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGraderecorderStudent class]
                                forKey:@"items"];
  return map;
}

@end
