/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorderConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API

#import "GTLGraderecorderConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeGraderecorderUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
