/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorderGradeEntry.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API
// Classes:
//   GTLGraderecorderGradeEntry (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGraderecorderGradeEntry
//

@interface GTLGraderecorderGradeEntry : GTLObject
@property (copy) NSString *assignmentKey;
@property (copy) NSString *entityKey;
@property (retain) NSNumber *score;  // longLongValue
@property (copy) NSString *studentKey;
@end
