/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLGraderecorderAssignmentCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API
// Classes:
//   GTLGraderecorderAssignmentCollection (0 custom class methods, 2 custom properties)

#import "GTLGraderecorderAssignmentCollection.h"

#import "GTLGraderecorderAssignment.h"

// ----------------------------------------------------------------------------
//
//   GTLGraderecorderAssignmentCollection
//

@implementation GTLGraderecorderAssignmentCollection
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLGraderecorderAssignment class]
                                forKey:@"items"];
  return map;
}

@end
