/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryGraderecorder.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API
// Classes:
//   GTLQueryGraderecorder (7 custom class methods, 6 custom properties)

#import "GTLQueryGraderecorder.h"

#import "GTLGraderecorderAssignment.h"
#import "GTLGraderecorderAssignmentCollection.h"
#import "GTLGraderecorderGradeEntry.h"
#import "GTLGraderecorderGradeEntryCollection.h"
#import "GTLGraderecorderStudentCollection.h"

@implementation GTLQueryGraderecorder

@dynamic assignmentKey, entityKey, fields, limit, order, pageToken;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"assignment_key"
                                forKey:@"assignmentKey"];
  return map;
}

#pragma mark -
#pragma mark "assignment" methods
// These create a GTLQueryGraderecorder object.

+ (id)queryForAssignmentDeleteWithEntityKey:(NSString *)entityKey {
  NSString *methodName = @"graderecorder.assignment.delete";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.entityKey = entityKey;
  query.expectedObjectClass = [GTLGraderecorderAssignment class];
  return query;
}

+ (id)queryForAssignmentInsertWithObject:(GTLGraderecorderAssignment *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"graderecorder.assignment.insert";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLGraderecorderAssignment class];
  return query;
}

+ (id)queryForAssignmentList {
  NSString *methodName = @"graderecorder.assignment.list";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLGraderecorderAssignmentCollection class];
  return query;
}

#pragma mark -
#pragma mark "gradeentry" methods
// These create a GTLQueryGraderecorder object.

+ (id)queryForGradeentryDeleteWithEntityKey:(NSString *)entityKey {
  NSString *methodName = @"graderecorder.gradeentry.delete";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.entityKey = entityKey;
  query.expectedObjectClass = [GTLGraderecorderGradeEntry class];
  return query;
}

+ (id)queryForGradeentryInsertWithObject:(GTLGraderecorderGradeEntry *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"graderecorder.gradeentry.insert";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLGraderecorderGradeEntry class];
  return query;
}

+ (id)queryForGradeentryListWithAssignmentKey:(NSString *)assignmentKey {
  NSString *methodName = @"graderecorder.gradeentry.list";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.assignmentKey = assignmentKey;
  query.expectedObjectClass = [GTLGraderecorderGradeEntryCollection class];
  return query;
}

#pragma mark -
#pragma mark "student" methods
// These create a GTLQueryGraderecorder object.

+ (id)queryForStudentList {
  NSString *methodName = @"graderecorder.student.list";
  GTLQueryGraderecorder *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLGraderecorderStudentCollection class];
  return query;
}

@end
